{"uuid": "f9dbbe28-78c5-4eec-9624-b7b2f7026912", "children": ["37ad0e7d-a9e0-4684-b56f-05b0e15e96c8"], "befores": [{"name": "prep_db", "status": "broken", "statusDetails": {"message": "psycopg2.OperationalError: FATAL:  password authentication failed for user \"postgres\"\n\n", "trace": "  File \"C:\\Users\\DimaNotebook\\Google Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DimaNotebook\\Google Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\DimaNotebook\\Google Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\DimaNotebook\\Google_Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\RabotyNET_pytest\\conftest.py\", line 14, in prep_db\n    prepare_db()\n  File \"C:\\Users\\DimaNotebook\\Google_Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\RabotyNET_pytest\\utilities\\db.py\", line 14, in prepare_db\n    password=DB_PASS, host=DB_HOST) as conn:\n  File \"C:\\Users\\DimaNotebook\\Google Drive\\SoftServe\\AutomationQC\\Selenium\\PyTest\\env\\lib\\site-packages\\psycopg2\\__init__.py\", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n"}, "start": 1566659074262, "stop": 1566659074705}], "start": 1566659074261, "stop": 1566659075383}