{"name": "test_update_company_name", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'backup.sql'", "trace": "@pytest.fixture(scope='session', autouse='True')\n    def prep_db():\n>       prepare_db()\n\n..\\conftest.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def prepare_db():\n        table_list = ['users', 'contact', 'address', 'claim', 'company', 'education', 'job',\n                      'pdf_resume', 'person', 'photo', 'requirement', 'resume', 'roles',\n                      'skill', 'user_role', 'vacancy', 'vacancy_resume',\n                      'verificationtoken']\n    \n        with psycopg2.connect(dbname=DB_NAME, user=DB_USER,\n                              password=DB_PASS, host=DB_HOST) as conn:\n            cur = conn.cursor()\n            for table in table_list:\n                cur.execute('TRUNCATE {} CASCADE'.format('public.' + table))\n    \n>           back_up = open(DB_FILE, 'r')\nE           FileNotFoundError: [Errno 2] No such file or directory: 'backup.sql'\n\n..\\utilities\\db.py:17: FileNotFoundError"}, "start": 1565795568458, "stop": 1565795568458, "uuid": "94a14aa5-55cf-4fb7-97b9-dcb12ebff291", "historyId": "108d8b600115b65fbab8bab440000afd", "fullName": "tests.test_update_company_name#test_update_company_name", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_company_name"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-Q2AH420"}, {"name": "thread", "value": "2000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_company_name"}]}