{"uuid": "903e921f-742e-4dab-a6b1-1cc73b47778a", "children": ["94a14aa5-55cf-4fb7-97b9-dcb12ebff291"], "befores": [{"name": "prep_db", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'backup.sql'\n", "trace": "  File \"C:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\Nataliya\\Desktop\\пари\\ATQC\\PYTEST\\RabotyNET_pytest\\conftest.py\", line 27, in prep_db\n    prepare_db()\n  File \"C:\\Users\\Nataliya\\Desktop\\пари\\ATQC\\PYTEST\\RabotyNET_pytest\\utilities\\db.py\", line 17, in prepare_db\n    back_up = open(DB_FILE, 'r')\n"}, "start": 1565795568462, "stop": 1565795568835}], "start": 1565795568462, "stop": 1565795568885}